### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by BatoolMM** [ArabR/arabr.github.io#2]
We need to add CoC - we can adapt one from an established community (e.g. the Carpentries) and then apply changes. This approach is used by other Open Source Communities!

**Comment by BatoolMM** [comment]
We will adapt it from [the Contributor Covenant](https://www.contributor-covenant.org/) but we need to make modifications. I've created a new file for [CoC in Notion](https://batool.notion.site/Code-of-Conduct-3e2f8c1c8a6a42e3964fe61687b21dd2). Please feel free to add your comments there!

**Comment by Hussain-Alsalman** [comment]
I would suggest to migrate CoC from notion to GitHub to track changes and deploy it automatically.
